"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-18 07:29:58.555805
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('epss_scores',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('epss', sa.Float(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('score_date', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_table('feed_syncs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feed', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kev_entries',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('vendor_project', sa.String(length=200), nullable=True),
    sa.Column('product', sa.String(length=200), nullable=True),
    sa.Column('vulnerability_name', sa.Text(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('required_action', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('known_ransomware_campaign_use', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cwes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('placed_on_market_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('vulnerabilities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('severity', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=200), nullable=True),
    sa.Column('published', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('aware_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_early_warning', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_notification', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_final_report', sa.DateTime(timezone=True), nullable=False),
    sa.Column('final_report_anchor', sa.String(length=16), nullable=False),
    sa.Column('fix_available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cve_id'], ['kev_entries.cve_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'cve_id', name='uq_incident_product_cve')
    )
    op.create_index(op.f('ix_incidents_cve_id'), 'incidents', ['cve_id'], unique=False)
    op.create_index(op.f('ix_incidents_product_id'), 'incidents', ['product_id'], unique=False)
    op.create_table('sboms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('spec_version', sa.String(length=16), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('component_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sboms_product_id'), 'sboms', ['product_id'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sbom_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('purl', sa.String(length=600), nullable=True),
    sa.Column('ecosystem', sa.String(length=32), nullable=True),
    sa.Column('cpe', sa.String(length=300), nullable=True),
    sa.Column('supplier', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sbom_id'], ['sboms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_product_id'), 'components', ['product_id'], unique=False)
    op.create_index(op.f('ix_components_purl'), 'components', ['purl'], unique=False)
    op.create_index(op.f('ix_components_sbom_id'), 'components', ['sbom_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fact_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'stage', 'language', 'version', name='uq_report_version')
    )
    op.create_index(op.f('ix_reports_incident_id'), 'reports', ['incident_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.String(length=64), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=True),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('affected_range', sa.Text(), nullable=True),
    sa.Column('in_kev', sa.Boolean(), nullable=False),
    sa.Column('epss', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'vulnerability_id', name='uq_match_component_vuln')
    )
    op.create_index(op.f('ix_matches_component_id'), 'matches', ['component_id'], unique=False)
    op.create_index(op.f('ix_matches_cve_id'), 'matches', ['cve_id'], unique=False)
    op.create_index(op.f('ix_matches_in_kev'), 'matches', ['in_kev'], unique=False)
    op.create_index(op.f('ix_matches_vulnerability_id'), 'matches', ['vulnerability_id'], unique=False)
    # ### end Alembic commands ###

    # --- audit_log is append-only: any UPDATE or DELETE raises ---------------------------
    op.execute("""
        CREATE OR REPLACE FUNCTION audit_log_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only: % not allowed', TG_OP
                USING ERRCODE = 'integrity_constraint_violation';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();
    """)
    # Belt and braces: also forbid TRUNCATE.
    op.execute("""
        CREATE TRIGGER trg_audit_log_no_truncate
        BEFORE TRUNCATE ON audit_log
        FOR EACH STATEMENT EXECUTE FUNCTION audit_log_append_only();
    """)


def downgrade() -> None:
    op.execute('DROP TRIGGER IF EXISTS trg_audit_log_no_truncate ON audit_log')
    op.execute('DROP TRIGGER IF EXISTS trg_audit_log_append_only ON audit_log')
    op.execute('DROP FUNCTION IF EXISTS audit_log_append_only()')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_vulnerability_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_in_kev'), table_name='matches')
    op.drop_index(op.f('ix_matches_cve_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_component_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_reports_incident_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_components_sbom_id'), table_name='components')
    op.drop_index(op.f('ix_components_purl'), table_name='components')
    op.drop_index(op.f('ix_components_product_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_sboms_product_id'), table_name='sboms')
    op.drop_table('sboms')
    op.drop_index(op.f('ix_incidents_product_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_cve_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_table('products')
    op.drop_table('kev_entries')
    op.drop_table('feed_syncs')
    op.drop_table('epss_scores')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
